# Site
repository: AishwaryaNachiya/modern-resume-theme
# favicon: images/favicon.ico (optional)

# Content configuration version
version: 2

# Personal info
name: Aishwarya Nachiya Subramanian
title: Data Analyst & Machine Learning Enthusiast
email: aishwaryanachiya.subramanian@students.mq.edu.au
phone: 0466029515
website: https://github.com/AishwaryaNachiya

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: AishwaryaNachiya
linkedin_username: aishwarya-nachiya-subramanian

# About Section
about_profile_image: images.jpeg
about_content: |
  I am a **Data Analyst** with a background in **Machine Learning, NLP, and AI**. I recently completed my **Master of Data Science** at Macquarie University. My work spans **data analysis, retrieval-augmented generation (RAG), and predictive modeling**. Passionate about uncovering insights from data and optimizing workflows through AI-driven automation.
  
  **Technical Skills:**
  - Programming: Python, R, SQL, MySQL, Neo4j, MongoDB
  - Machine Learning & Data Science: Statistical Modeling, NLP, Big Data
  - Cloud & Platforms: Azure Cognitive Services, Oracle Cloud
  - Tools: Power BI, Tableau, Excel, Git, Jupyter Notebook

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: RAG-based Pre-Consultation Reports
        link: https://github.com/AishwaryaNachiya/Final-Report-COMP8240
        link_text: GitHub Repo
        additional_links:
          - title: GitHub Repo
            icon: fab fa-github
            url: https://github.com/AishwaryaNachiya/Final-Report-COMP8240
        quote: >
          Developed a **Retrieval-Augmented Generation (RAG) system** for medical pre-consultation reports.
        description: |
          Integrated **Azure Cognitive Services, LangChain, and ChatGPT-4** to process patient records while ensuring **PII removal**. Enhanced workflow efficiency for **healthcare documentation**.

      - layout: left
        border: weak
        title: Stock Market Analysis & Prediction
        link: https://github.com/AishwaryaNachiya/Stock-Market-Analysis
        link_text: GitHub Repo
        additional_links:
          - title: GitHub Repo
            icon: fab fa-github
            url: https://github.com/AishwaryaNachiya/Stock-Market-Analysis
        quote: >
          Forecasting **tech stock prices** using **Long Short-Term Memory (LSTM) models**.
        description: |
          Extracted data using **yfinance**, performed **time series analysis**, assessed risks, and predicted **future stock prices**.

  - title: Experience
    layout: list
    content:
      - layout: right
        title: GlobalMedics.AI
        sub_title: Data Analysis Intern
        caption: Jan 2024 - June 2024
        description: |
          - Built a **RAG model** for **pre-consultation reports** in **Azure Cognitive Search**.
          - Applied **PII removal techniques** for **healthcare data privacy**.
          - Automated **structured data extraction** using **Azure Form Recognizer**.

      - layout: right
        title: OSHC Educator
        sub_title: Childcare Support
        caption: April 2024 - Present
        description: |
          - Facilitated activities to promote **children's physical, emotional, and social development**.
          - Ensured compliance with **child safety standards**.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Macquarie University, Sydney
        sub_title: Master of Data Science
        caption: 2022 - 2024
        quote: >
          Specialization in **Machine Learning & AI**.
        description: |
          Coursework included **Big Data, NLP, Predictive Analytics, and Statistical Modelling**.

      - layout: top-right
        title: Rajalakshmi Institute of Technology, Chennai
        sub_title: Bachelor of Engineering (Electronics & Communication)
        caption: 2017 - 2021
        description: |
          Focused on **Signal Processing, Embedded Systems, and Python Programming**.

  - title: Certifications
    layout: list
    content:
      - layout: left
        title: Microsoft Power BI Certification
        caption: Ongoing
        description: |
          Developing expertise in **data visualization and business intelligence**.
      - layout: left
        title: LangChain Chat with Your Data
        caption: Completed
        description: |
          Learned **text preprocessing, tokenization, and retrieval-augmented generation**.

  - title: A Little More About Me
    layout: text
    content: |
      **Interests:**
      - Exploring **AI-powered automation**
      - Cooking & **food tourism**
      - **Budget-friendly travel** adventures

# Footer
footer_show_references: true

# Build settings
theme: modern-resume-theme
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
